/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#191c1d",
        "on-error-container": "#93000a",
        "surface-dim": "#cfdaf1",
        "secondary-fixed": "#ffdf97",
        "on-secondary-fixed-variant": "#5a4400",
        "secondary-container": "#fece54",
        "on-tertiary": "#ffffff",
        "background": "#f9f9ff",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#c5c7c8",
        "secondary-fixed-dim": "#efc047",
        "on-tertiary-fixed-variant": "#454748",
        "primary-container": "#003d7a",
        "tertiary-fixed": "#e1e3e4",
        "on-primary-fixed-variant": "#134684",
        "on-secondary-fixed": "#251a00",
        "on-background": "#111c2c",
        "on-primary-fixed": "#001b3d",
        "inverse-surface": "#263142",
        "tertiary-container": "#3b3e3f",
        "surface-container-highest": "#d8e3fa",
        "on-primary-container": "#81aaed",
        "on-primary": "#ffffff",
        "on-secondary-container": "#735700",
        "surface-container-low": "#f0f3ff",
        "inverse-primary": "#a8c8ff",
        "tertiary": "#252829",
        "outline-variant": "#c3c6d2",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#ebf1ff",
        "on-surface": "#111c2c",
        "surface-container": "#e7eeff",
        "error-container": "#ffdad6",
        "surface-bright": "#f9f9ff",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#a8c8ff",
        "on-tertiary-container": "#a7a9aa",
        "surface": "#f9f9ff",
        "primary": "#002753",
        "surface-variant": "#d8e3fa",
        "secondary": "#775a00",
        "surface-container-high": "#dee8ff",
        "outline": "#737781",
        "primary-fixed": "#d6e3ff",
        "on-surface-variant": "#434750",
        "surface-tint": "#335f9d"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "margin-desktop": "32px",
        "container-max": "1440px",
        "sidebar-width": "280px",
        "margin-mobile": "16px",
        "base": "8px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "label-sm": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "1", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.25", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
